### PR TITLE
Some fixes for `--script-exec`/`--script-sh`

### PR DESCRIPTION
**Pull request by zevweiss**
These patches address issue #6 (for me, at least) and make a couple other minor fixes.

### CODE REVIEW

**Comment by zevweiss** [comment]
Hmm, though now I'm realizing 480988a will probably break non-intramfs situations...updated to make including the tmpfs mount conditional on `!need_initramfs`.

**Comment by amluto** [comment]
The last three changes look good.  For the first two, could you respin them as:

1. Add initargs but make no other changes (and change '; ' to ';' to avoid changing anything).
2. Add the improved logic?

Also, could you rebase and add Signed-off-by to your commit messages?

**Comment by zevweiss** [comment]
OK, now updated accordingly (assuming I understood correctly -- if not let me know).

**Comment by amluto** [comment]
All done.  Thanks!

**Pull request merged**
