### PR TITLE
Miscellaneous fixes/features

### PR DESCRIPTION
**Pull request by zevweiss**

### CODE REVIEW

**Comment by fzago-cray** [comment]
Hi, is there any plan to merge this and the other PRs?

**Comment by amluto** [comment]
I've applied all but the hostname thing.  I think it should be reworked to use virtme_data rather than passing an extra argument all over the place.

It would be really nice if we could find a way to make virtme_data work without initramfs, too.

**Comment by zevweiss** [comment]
Hmm -- that would be an easy enough change to make, though honestly having it as a qemu command-line flag was a significant part of my motivation for doing it in the first place.  I've been using virtme as part of a larger scripted process for running things across a bunch of virtualized systems concurrently, and it's nice to be able to easily identify which process is which guest in `top` and such on the host by giving them meaningful names.  Is there a particular reason using the command-line flag approach is undesirable?

**Comment by amluto** [comment]
What I mean is: the code is a bit messy.  There's already a 'config' object passed through the initramfs code, so rather than *also* passing hostname, it would be nicer to put the hostname in the config.

But, on second thought, this is entirely the wrong solution.  Can you make this work just like virtme_stty_con?  Then you wouldn't need initramfs.

Hmm.  Maybe it should be called --name not --hostname, but I'm ambivalent about that.

**Comment by zevweiss** [comment]
Ah, yes, that does lead to a much cleaner implementation (source branch updated accordingly).  And while I'm likewise not strongly opinionated either way, I did change the flag name to --name, my only slight inclination being that it's consistent with the name of the qemu flag it involves.

**Comment by zevweiss** [comment]
(And now updated once more to trim out a bit of cruft remaining from the original version -- don't need the hostname binary in the initramfs anymore, obviously.)

**Comment by amluto** [comment]
Nice!

**Comment by zevweiss** [comment]
Sorry, PR closed but no merge or cherry-pick that I can see...any remaining problems?

**Comment by amluto** [comment]
I meant to merge it, but I appear to have failed...

**Pull request merged**
